### ISSUE TITLE
[IR/Compiler] Add in pre/post callbacks for blocks

### ISSUE THREAD

**Issue by tabularelf** [katsaii/catspeak-lang#118]
### What is your feature request?

Allow the ir to include pre/post callbacks for blocks.
Right now I am doing certain with() functionality support, that requires me to execute push/pop stacks.
But doing `break`/`continue`/`return` breaks any pop conditions.
I can deal with `break`, but I cannot deal with `continue`/`return`.

### Please describe in detail how you expect this new feature to behave.

Changing it from
`ir.pushBlock([inherit=false])`
`ir.popBlock([location=undefined])`
to 
`ir.pushBlock([inherit=false], [pushcallback=undefined])`
`ir.popBlock([popcallback=undefined], [location=undefined])`

If a push/pop callback condition is passed through, it will execute those first prior to running the code between the blocks each time. Meaning that I can force execute a push/pop statement in between.

**Comment by katsaii** [comment]
Looking back at this, I would rather just implement this as a instruction. E.g. a `WITH` instruction.
