### ISSUE TITLE
[IR/Compiler] Add .createCall0-3 support

### ISSUE THREAD

**Issue by tabularelf** [katsaii/catspeak-lang#120]
### What is your feature request?

I’ve been doing a lot of `.createCall` as I’ve been finding it more and more necessary to pass around and define specific functions. But a lot of the time I don’t need to loop and pass a bunch of arguments. Calling and passing arguments directly should also make things a bit faster. 

### Please describe in detail how you expect this new feature to behave.

Similar to .createCall, except that each program can be executed directly with up to x arguments, up to three. Each function accepting one more additional argument than the last. 

`return ir.createCall0(ir.createGet("self"), lexer.getLocation()))`

I have similar code here extended for with() scope handle. Since I need to be able to pass values into them.

**Comment by tabularelf** [comment]
Reopened this, I can’t recall if the IR can do this

**Comment by katsaii** [comment]
I'd prefer this be on the code generator side by updating `__catspeak_expr_call__` to include 
- `__catspeak_expr_call_0__`
- `__catspeak_expr_call_1__`
- `__catspeak_expr_call_2__`
- `__catspeak_expr_call_3__`

**Comment by tabularelf** [comment]
Works for me
