### ISSUE TITLE
Add in a way to check if a global exists from CatspeakFunction.

### ISSUE THREAD

**Issue by tabularelf** [katsaii/catspeak-lang#31]
We have `.getGlobal()` and `.setGlobal()`, which both are great! But there's no way to check if a specific global does exist or not.
Adding in a way would at the very least make it easier on my end to check for specific globals, rather than relying on `undefined`.

**Comment by katsaii** [comment]
I've added `existsGlobal` and `getGlobalNames` for now. I'm planning on totally refactoring everything soon so these names will probably change to `globalExists` and `globalGetNames` down the line. Should appear in version 2.3.0
