### ISSUE TITLE
Ability to import functions from other script files within the script itself

### ISSUE THREAD

**Issue by AlubJ** [katsaii/catspeak-lang#35]
Similarly to languages like Javascript and Python, would it be possible to add the ability to import functions from other script files?

**Comment by katsaii** [comment]
Because Catspeak doesn't have a concept of modules, there isn't a way to do this currently. If you could draft up an idea of how you would expect it to work, I can take it into consideration when I work on something like that.

**Comment by AlubJ** [comment]
My current idea would be to have any imported scripts be compiled, and any functions that would want to be used in a separate script would be differentiated with something similar to c++'s `declspec()` function (perhaps `extern` would be more appropriate of a keyword).

Here is an idea of how it would be syntactically in catspeak.

addFunction.txt
```
add = extern(a, b) {
    return a+b
}
```

main.txt
```
import "addFunction.txt"
print(add(1, 2))
```

I could 100% be pulling this out of thin air since I don't know how potentially difficult it would be.

**Comment by katsaii** [comment]
My main concern is that Catspeak has no concept of a file structure. I reckon I would want to implement this in a fairly generic way that can be customised, without depending on any one style. In other words: maybe one person wants `import "a.meow"` to look for files in a "mods" folder (`mods/a.meow`), but another person just wants them to be in the root directory.

I'm not too interested into visibility modifiers/picking which functions to export. I'll think about it, but no promises. I would rather just have it import everything.

**Comment by katsaii** [comment]
Although not supported through an `import` keyword, it is possible to pre-compile multiple files into a single script, so I'm going to close this.
