### ISSUE TITLE
Feature to pick up arguments passed into a compiled Catspeak function

### ISSUE THREAD

**Issue by JujuAdams** [katsaii/catspeak-lang#52]
Couldn't find this one in the old v2 docs, but it'd be handy to be able to pass arguments into a Catspeak compiled functions and pick them up inside e.g.

```gml
func = Catspeak.compileGML(_asg);
func(x, y);
```
```catspeak
draw_text($param0, $param1. "Hello");
```
Or something similar. We can achieve a similar effect by calling `.setSelf()` on the function but direct argument passing would be easier to use in many situations.

**Comment by katsaii** [comment]
I thought about exposing a way to do this, but I think you might just want to return a function and use named arguments on that instead:
```js
funcMain = Catspeak.compileGML(_asg);
var func = funcMain();

func(x, y);
```
```py
return fun(x, y) {
  draw_text(x, y, "Hello");
}
```

**Comment by JujuAdams** [comment]
Yeah ok! I can live with that.

Edit: When you get round to documentation it'd be good to cover this use case.
