### ISSUE TITLE
Defining structs without leading comma at end crashes

### ISSUE THREAD

**Issue by tabularelf** [katsaii/catspeak-lang#53]
Was experimenting with structs, when I've noticed something odd.
This bit of code here
```gml
var asg = Catspeak.parseString(@'
	
return {
	foo: "bar",
	a_number: 0,
	a_string: "Hello World!"
}
');
func = Catspeak.compileGML(asg);
var result = func();
show_debug_message(json_stringify(result, true));
```
Is causing Catspeak to crash. Unless I add a comma at the end. Then it works just fine?
```gml
return {
	foo: "bar",
	a_number: 0,
	a_string: "Hello World!",
}
```
[crash.txt](https://github.com/katsaii/catspeak-lang/files/11776496/crash.txt)

**Comment by katsaii** [comment]
That's really weird, the commas should be entirely optional.

**Comment by katsaii** [comment]
Figured out the issue, it's somewhat related to #56. I'll have to make a breaking change to the lexer to support this (which should be fine).
