### ISSUE TITLE
Question regarding curly bracket position in function definition

### ISSUE THREAD

**Issue by JujuAdams** [katsaii/catspeak-lang#56]
Is it intentional that
```
main = fun()
{
    //Body
}
```
throws an error whereas
```
main = fun() {
    //Body
}
```
does not?

**Comment by katsaii** [comment]
Yes, each new line character is considered a statement termination. I might try and see if I can figure out a way to make this syntax work, but no promises.

**Comment by JujuAdams** [comment]
If that's the syntax that's the syntax, I think it's ok to be opinionated here.

If possible, it would be good to slide a helpful comment into the error message to point people to the right syntax.
