### ISSUE TITLE
Creating a new environment and using `.parseString()` refers to Catspeak env.

### ISSUE THREAD

**Issue by tabularelf** [katsaii/catspeak-lang#87]
### What version of Catspeak are you using?

`3.0.0-beta3`

### What happened?

While I was making a separate environment to add in keywords and execute via `env.parseString(_str)`, I was getting strange compiling errors until I realized that it's just accessing Catspeak itself. (On a off note, there's a memory leak here too)

I think it should be changed to something like this instead.
```gml
    static parseString = function (src) {
        var buff = __catspeak_create_buffer_from_string(src);
        var result = parse(buff);
	buffer_delete(buff);
	return result;
    };
```

Code that demonstrates this problem:
```gml
env = new CatspeakEnvironment();
env.renameKeyword(
        "//", "div",
        "--", "//"
);
// Fails to parse due to pointing towards Catspeak in .parseString
var asg = env.parseString(@"// A Comment!
    num = 42;
    return num;
");
func = env.compileGML(asg);
show_debug_message(func());
```

**Comment by katsaii** [comment]
Good catch, this will make it into the 3.0.0 release.
